# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5e183ae90f93ba2604a253feca72f417d2529e0b9434457d4720e51490156b1bf3c90e7ae4da85d4d46b6b211fb0cae6c82eebac10d36973cade7e826d56d73

test:
  secret_key_base: ddb00b5bae44ac07e67cec6b450b3dd877c77a622515c8e962ce522c875d47ce246afc6d932d3e840383a4aca081b4e70f4b23c8f2f6260fb0eda79b758647fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
